import { PokemonCard } from './types';

export const POKEMON_CARDS: PokemonCard[] = [
  {
    id: 'iono-sv2-269',
    name: 'Iono #269 SIR',
    emoji: '👩',
    number: '269',
    type: 'SIR',
    expansion: 'Paldea Evolved',
    buyUnder: 20,
    resaleMin: 28,
    resaleMax: 35,
    imageUrl: 'https://images.pokemontcg.io/sv2/269.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Paldea-Evolved/Iono-PAL269'
  },
  {
    id: 'magikarp-sv2-203',
    name: 'Magikarp #203 IR',
    emoji: '🐟',
    number: '203',
    type: 'IR',
    expansion: 'Paldea Evolved',
    buyUnder: 180,
    resaleMin: 120,
    resaleMax: 150,
    imageUrl: 'https://images.pokemontcg.io/sv2/203.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Paldea-Evolved/Magikarp-PAL203'
  },
  {
    id: 'charizard-sv3-223',
    name: 'Charizard ex #223 SIR',
    emoji: '🔥',
    number: '223',
    type: 'SIR',
    expansion: 'Obsidian Flames',
    buyUnder: 70,
    resaleMin: 90,
    resaleMax: 120,
    imageUrl: 'https://images.pokemontcg.io/sv3/223.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Obsidian-Flames/Charizard-ex-V3-OBF223'
  },
  {
    id: 'arceus-swsh12pt5-gg70',
    name: 'Arceus VSTAR GG70',
    emoji: '⭐',
    number: 'GG70',
    type: 'GG / VSTAR',
    expansion: 'Crown Zenith',
    buyUnder: 110,
    resaleMin: 75,
    resaleMax: 95,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/GG70_hires.png',
    cardmarketUrl: 'https://www.cardmarket.com/it/Pokemon/Products/Singles/Crown-Zenith/Arceus-VSTAR-CRZGG70'
  },
  {
    id: 'giratina-swsh12pt5-gg69',
    name: 'Giratina VSTAR GG69',
    emoji: '✨',
    number: 'GG69',
    type: 'GG / VSTAR',
    expansion: 'Crown Zenith',
    buyUnder: 160,
    resaleMin: 120,
    resaleMax: 150,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/GG69_hires.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Crown-Zenith/Giratina-VSTAR-CRZGG69'
  },
  {
    id: 'dragonite-swsh7-192',
    name: 'Dragonite V Alt Art #192',
    emoji: '🐉',
    number: '192',
    type: 'Alt Art',
    expansion: 'Evolving Skies',
    buyUnder: 160,
    resaleMin: 180,
    resaleMax: 220,
    imageUrl: 'https://images.pokemontcg.io/swsh7/192.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Evolving-Skies/Dragonite-V-EVS192'
  },
  {
    id: 'aerodactyl-swsh11-180',
    name: 'Aerodactyl V Alt Art #180',
    emoji: '🔬',
    number: '180',
    type: 'Alt Art',
    expansion: 'Lost Origin',
    buyUnder: 90,
    resaleMin: 120,
    resaleMax: 150,
    imageUrl: 'https://images.pokemontcg.io/swsh11/180.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Lost-Origin/Aerodactyl-V-LOR180'
  },
  {
    id: 'lugia-swsh12-186',
    name: 'Lugia V Alt Art #186',
    emoji: '🐉',
    number: '186',
    type: 'Alt Art',
    expansion: 'Silver Tempest',
    buyUnder: 180,
    resaleMin: 190,
    resaleMax: 230,
    imageUrl: 'https://images.pokemontcg.io/swsh12/186.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Silver-Tempest/Lugia-V-SIT186'
  },
  {
    id: 'tyranitar-sv2-222',
    name: 'Tyranitar ex #222 IR',
    emoji: '🦖',
    number: '222',
    type: 'IR',
    expansion: 'Paldea Evolved',
    buyUnder: 20,
    resaleMin: 30,
    resaleMax: 40,
    imageUrl: 'https://images.pokemontcg.io/sv2/222.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Paldea-Evolved/Tyranitar-PAL222'
  },
  {
    id: 'chienpao-sv2-261',
    name: 'Chien-Pao ex #261 SIR',
    emoji: '🐲',
    number: '261',
    type: 'SIR',
    expansion: 'Paldea Evolved',
    buyUnder: 20,
    resaleMin: 30,
    resaleMax: 40,
    imageUrl: 'https://images.pokemontcg.io/sv2/261.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Paldea-Evolved/Chien-Pao-ex-PAL261'
  },
  {
    id: 'pikachu-swsh12pt5-160',
    name: 'Pikachu Secret Rare #160',
    emoji: '⚡',
    number: '160',
    type: 'Secret Rare',
    expansion: 'Crown Zenith',
    buyUnder: 20,
    resaleMin: 30,
    resaleMax: 40,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5/160.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Crown-Zenith/Pikachu-CRZ160'
  },
  {
    id: 'glaceon-swsh12pt5-gg40',
    name: 'Glaceon VSTAR GG40',
    emoji: '❄️',
    number: 'GG40',
    type: 'GG / VSTAR',
    expansion: 'Crown Zenith',
    buyUnder: 40,
    resaleMin: 35,
    resaleMax: 50,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/GG40_hires.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Crown-Zenith/Glaceon-VSTAR-CRZGG40'
  },
  {
    id: 'leafeon-swsh12pt5-gg35',
    name: 'Leafeon VSTAR GG35',
    emoji: '🌿',
    number: 'GG35',
    type: 'GG / VSTAR',
    expansion: 'Crown Zenith',
    buyUnder: 25,
    resaleMin: 30,
    resaleMax: 45,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/GG35_hires.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Crown-Zenith/Leafeon-VSTAR-CRZGG35'
  },
  {
    id: 'suicune-swsh12pt5-gg38',
    name: 'Suicune V GG38',
    emoji: '🐶',
    number: 'GG38',
    type: 'GG / V',
    expansion: 'Crown Zenith',
    buyUnder: 20,
    resaleMin: 30,
    resaleMax: 40,
    imageUrl: 'https://images.pokemontcg.io/swsh12pt5gg/GG38_hires.png',
    cardmarketUrl: 'https://www.cardmarket.com/en/Pokemon/Products/Singles/Crown-Zenith/Suicune-V-CRZGG38'
  }
];
